#https://hub.docker.com/r/gnzsnz/ib-gateway
version: '3.8'
services:
  ib-gateway:
    image: ghcr.io/extrange/ibkr:latest #latest, stable, 10.21, 10.21.1p etc
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000 # See FAQ
    restart: always

    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: gateway
      #
      # Variables prefixed with IBC_ override IBCAlpha`s config.ini:
      IBC_TradingMode: "${TRADING_MODE}"
      IBC_ReadOnlyApi: 'no'
      IBC_ReadOnlyLogin: 'no'
      IBC_AcceptNonBrokerageAccountWarning: 'yes'
      IBC_AcceptIncomingConnectionAction: 'accept'    
      IBC_ExistingSessionDetectedAction: 'primary'
      IBC_BypassOrderPrecautions: 'yes'
      IBC_BypassBondWarning: 'yes'
      IBC_BypassNegativeYieldToWorstConfirmation: 'yes'
      IBC_BypassCalledBondWarning: 'yes'
      IBC_BypassSameActionPairTradeWarning: 'yes'
      IBC_BypassPriceBasedVolatilityRiskWarning: 'yes'
      IBC_BypassUSStocksMarketDataInSharesWarning: 'yes'
      IBC_BypassRedirectOrderWarning: 'yes'
      IBC_BypassNoOverfillProtectionPrecaution: 'yes'
      IBC_ColdRestartTime: '20:00'
      IBC_AutoRestartTime: '20:00'

    networks:
      - ib_network

  options-butterfly-condor:
    build:
      context: ./environment/bot    
    env_file: 
      - .env
    restart: always
    depends_on:
      - ib-gateway
    environment:
      INTERACTIVE_BROKERS_PORT: ${INTERACTIVE_BROKERS_PORT}
      INTERACTIVE_BROKERS_CLIENT_ID: ${INTERACTIVE_BROKERS_CLIENT_ID}
      INTERACTIVE_BROKERS_IP: ${INTERACTIVE_BROKERS_IP}
    networks: 
      - ib_network

networks: 
  ib_network: 
    driver: bridge
