services:
  ib-gateway:
    # image: grzesir/ib-gateway:stable
    image: ghcr.io/gnzsnz/ib-gateway:stable
    platform: linux/arm64
    restart: always
    env_file: 
      - .env
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE}
      TWS_ACCEPT_INCOMING: 'accept'
      VNC_SERVER_PASSWORD: '12345678'
      READ_ONLY_API: 'no'
      TWOFA_TIMEOUT_ACTION: 'restart'
      BYPASS_WARNING: 'yes'
      AUTO_RESTART_TIME: '11:59 PM'
      TWS_COLD_RESTART: '11:59 PM'
      RELOGIN_AFTER_TWOFA_TIMEOUT: 'yes'
      TIME_ZONE: America/New_York
      TZ: America/New_York
    networks:
      - ib_network
    ports:
      - 5900:5900
      
  strategy:
    build:
      context: ./environment/bot    
    env_file: 
      - .env
    restart: always
    depends_on:
      - ib-gateway
    environment:
      INTERACTIVE_BROKERS_PORT: ${INTERACTIVE_BROKERS_PORT}
      INTERACTIVE_BROKERS_CLIENT_ID: ${INTERACTIVE_BROKERS_CLIENT_ID}
      INTERACTIVE_BROKERS_IP: ${INTERACTIVE_BROKERS_IP}
      TZ: America/New_York

    networks: 
      - ib_network

networks: 
  ib_network: 
    driver: bridge
